// This file is generated by `../drug-list/Makefile`, based on the FDA's published database of all approved drugs
import ingredients from "../drug-list/ingredients.json";

export const MEDICATION_LIST = ingredients;
